# Generated by Django 2.1 on 2018-09-06 08:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcontent',
            name='blogtitle',
        ),
        migrations.AddField(
            model_name='blogcontent',
            name='title',
            field=models.CharField(default=datetime.datetime(2018, 9, 6, 8, 35, 50, 725014, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogcontent',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='Blogtitle',
        ),
    ]
