# Generated by Django 2.1 on 2018-09-06 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180906_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcontent',
            name='text',
            field=models.TextField(),
        ),
    ]
