# Generated by Django 2.1 on 2018-09-07 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogcontent_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcontent',
            name='date_added',
            field=models.DateTimeField(),
        ),
    ]
