# Generated by Django 2.1 on 2018-09-07 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180907_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcontent',
            name='owner',
        ),
        migrations.AlterField(
            model_name='blogcontent',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
