# Generated by Django 2.1 on 2018-09-10 07:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_aboutme'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
